### ISSUE TITLE
Feature request. Early stopping

### ISSUE THREAD

**Issue by FiksII** [Evolutionary-Intelligence/pypop#175]
Good day. If it possible to add 'early_stopping' feature? Sometimes I want to stop the process if it's stuck. 
I can add it.

**Comment by Evolutionary-Intelligence** [comment]
This is a good idea to add the interesting 'early_stopping' feature. Welcome to contribute this feature. Thanks very much for your kindly support again.

**Comment by FiksII** [comment]
> This is a good idea to add the interesting 'early_stopping' feature. Welcome to contribute this feature. Thanks very much for your kindly support again.

How should I test it? It seems you have a lot of "personal" tests, but no one general tests.

**Comment by Evolutionary-Intelligence** [comment]
You can write a simple test case. We (at least two core developers of this libary) will check and test it. After passing our test, we will add it in the new version (0.0.76).

**Comment by Evolutionary-Intelligence** [comment]
@FiksII We have upgraded your testing code as follows: https://github.com/Evolutionary-Intelligence/pypop/blob/main/pypop7/optimizers/core/_test_optimizer.py. In your initial version, only the one test case is used.

**Comment by Evolutionary-Intelligence** [comment]
@FiksII We also upgraded your Python code for class `optimizer`: https://github.com/Evolutionary-Intelligence/pypop/blob/main/pypop7/optimizers/core/optimizer.py. For two private members, we use `_` as the prefix as a standard Python practice.
