### ISSUE TITLE
Add Arxiv article resource link to readme

### ISSUE THREAD

**Issue by impredicative** [Evolutionary-Intelligence/pypop#82]
Perhaps the following link can be added to the readme (if it isn't present already):

https://arxiv.org/abs/2212.05652

**Comment by Evolutionary-Intelligence** [comment]
Thanks very much for your suggestion. We will add it in the near future. Since this library is still actively updated, we will provide an updated version for the arxiv paper.

**Comment by Evolutionary-Intelligence** [comment]
@impredicative Now we have added the arxiv link in README.
