### ISSUE TITLE
No module named 'pypop7.optimizers.bo'

### ISSUE THREAD

**Issue by SaeednHT** [Evolutionary-Intelligence/pypop#89]
Thank you for providing such an invaluable collection. I have checked the "setup.cfg" and found that Bayesian Optimization (BO) is not included yet (No module named 'pypop7.optimizers.bo' and LAMCTS is not available). Please add BO so that we can try this method using pypop7.

**Comment by Evolutionary-Intelligence** [comment]
Thanks for your interest. We will update the pypi package in the next month. Since LAMCTS has not been well tested by us, we will accelerate the test procedure in the next two weeks and add it in the next version.
